version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  garageRemote:
    image: garage-remote
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  garageRemoteFrontApp:
     image: garage-remote-front-app
     build:
       context: ../garage-remote-front-app
       dockerfile: Dockerfile
     ports:
       - "3000:3000"
       - "5000:5000"
     restart: always
     depends_on:
       - rabbitmq
       - garageRemote
